matrix:
- name: asciidoc source py spell check configuration
  aspell:
    lang: en
    d: en_US
  sources:
  - documentation/*.asciidoc 
  dictionary:
    wordlists:
    - en-devonfw.dict
    output: en-devonfw.dic
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true    
      escapes: '^.*[\/\\][^\/\\]+$'
  - pyspelling.filters.context:
      context_visible_first: true    
      escapes: "\b([A-Z]+)([a-z0-9]+[A-Z])+([a-z0-9]*)+[A-Za-z0-9]\b"
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\-~]
      delimiters:
      # Ignore multiline content between fences (fences can have 4 or more hyphens)
      # ----
      # content
      # ----
      - open: '(?s)^(?P<open> *-{4,})$'
        close: '^(?P=open)$'
