--- 
matrix: 
  - 
    aspell: 
      d: en_US
      lang: en
    dictionary: 
      output: en-devonfw.dic
      wordlists: 
        - en-devonfw.dict
    name: "asciidoc source py spell check configuration"
    pipeline: 
      - 
        pyspelling.filters.url: ~
      - 
        escapes: "\\\\[\\\\[a-z]+((\\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?~]"
        pyspelling.filters.context: ~
      - 
        context_visible_first: true
        delimiters: 
          - 
            close: ^(?P=open)$
            open: "(?s)^(?P<open> *-{4,})$"
        escapes: "\\\\[\\\\-~]"
        pyspelling.filters.context: ~
    sources: 
      - documentation/*.asciidoc
