:toc: macro

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]
:idprefix:
:idseparator: -
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

= Angular Electron

== Add Electron to an Angular application
This cookbook recipe explains how to integrate Electron in an Angular 6+ application. https://electronjs.org/[Electron] is a framework for creating native applications with web technologies like JavaScript, HTML, and CSS. As an example, very well known applications as Visual Studio Code, Atom, Slack or Skype (and many more) are using Electron too. 

NOTE: At the moment of this writing Angular 7.2.3 and Electron 4.0.2 were the versions available. 

Here are the steps to achieve this goal. Follow them in order. 

=== Add Electron and other relevant dependencies
There are two different approaches to add the dependencies in the `package.json` file: 

* Writing the dependencies directly in that file.
* Installing using `npm install` or `yarn add`. 

IMPORTANT: Please remember if the project has a `package-lock.json` or `yarn.lock` file use `npm` or `yarn` respectively.

In order to add the dependencies directly in the `package.json` file, include the following lines in the `devDependencies` section:

[source, json]
----
"devDependencies": {
...
    "@angular-builders/custom-webpack": "9.0.0",
    "electron": "8.0.1",
    "electron-builder": "22.3.2",
    "electron-reload": "1.5.0",
    "npm-run-all": "4.1.5",
    "wait-on": "4.0.0",
    "webdriver-manager": "12.1.7",
...
},
----

As indicated above, instead of this `npm install` can be used:

[source, bash]
----
$ npm install -D electron electron-builder electron-reload npm-run-all wait-on webdriver-manager 
----

Or with `yarn`:

[source, bash]
----
$ yarn add -D electron electron-builder electron-reload npm-run-all wait-on webdriver-manager
----

=== Add Electron build configuration

In order to configure electron builds properly a `electron-builder.json` must be included in the root folder of the application. For more information and fine tuning please refer to the https://www.electron.build/configuration/configuration[Electron Builder official documentation].

The contents of the file will be something similar to the following:

[source, json]
----
{
  "productName": "app-name",
  "directories": {
    "output": "release/"
  },
    "files": [
        "**/*",
        "!**/*.ts",
        "!*.code-workspace",
        "!LICENSE.md",
        "!package.json",
        "!package-lock.json",
        "!src/",
        "!e2e/",
        "!hooks/",
        "!angular.json",
        "!_config.yml",
        "!karma.conf.js",
        "!tsconfig.json",
        "!tslint.json"
    ],
  "win": {
    "icon": "dist",
    "target": [
      "portable"
    ]
  },
  "mac": {
    "icon": "dist",
    "target": [
      "dmg"
    ]
  },
  "linux": {
    "icon": "dist",
    "target": [
      "AppImage"
    ]
  }
}
----

Theres two important things in this file:
  
  1. "output": this is where electron builder is going to build our application

  2. "icon": in every OS possible theres an icon parameter, the route to the icon folder that will be created after building with angular needs to be used here. This will make it so the electron builder can find the icons and build.

=== Create the necessary typescript configurations

In order to initiate electron in an angular app we need to modify the `tsconfig.json` file and create a new one named `tsconfig-serve.json` in the root folder.

==== tsconfig.json

This file needs to be modified to add the `main.ts` and `src/\**/*` folders excluding the `node_modules`:

[source,json]
----
{
....
  },
  "include": [
    "main.ts",
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
....
}
----

==== tsconfig-serve.json

In the root, `tsconfig-serve.json` needs to be created. This typescript config file is going to be used when we serve electron:

[source, json]
----
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "types": ["node"],
    "lib": ["es2017", "es2016", "es2015", "dom"]
  },
  "include": ["main.ts"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
----

=== Modify angular.json

`angular.json` has to to be modified so the project is built inside _/dist_ without an intermediate folder and include the reference to the custom Webpack configuration.

[source,TypeScript]
----
{
....
  "architect": {
    ....
    "build": {
      "options": {
        ....
        "outputPath": "dist",
        ....
        "customWebpackConfig": {
          "path": "./angular.webpack.js"
        }
      }
    }
  ....
}
----

=== Add Angular Electron directives
In order to use Electron's webview tag and its methods inside an Angular application our project needs the directive `webview.directive.ts` file. We recommend to create this file inside a **shared** module folder, although it has to be declared inside the main module `app.module.ts`.

.File webview.directive.ts
[source,TypeScript]
----
import { Directive } from '@angular/core';

@Directive({
  selector: 'webview',
})
export class WebviewDirective {}

----

=== Add access Electron APIs

To call Electron APIs from the Renderer process, install **ngx-electron** package or create **your own ElectronService**.

With `npm`:
[source, bash]
----
$ npm install ngx-electron --save
----

Or with `yarn`:

[source, bash]
----
$ yarn add ngx-electron --save
----

This package contains a module named *NgxElectronModule* which exposes Electron APIs through a service called *ElectronService*.

If you decide to implement your own ElectronService, please refer to https://github.com/devonfw/devon4ng/blob/develop/samples/ElectronTest/src/app/core/service/electron/electron.service.ts[this file] in the ElectronTest sample.

==== Update `app.module.ts` and `app-routing.module.ts`

As an example, the `webview.directive.ts` file is located inside a `shared` module:

.File app.module.ts
[source,TypeScript]
----
// imports
import { NgxElectronModule } from 'ngx-electron';
import { WebviewDirective } from './shared/directives/webview.directive';

@NgModule({
  declarations: [AppComponent, WebviewDirective],
  imports: [
    ...
    NgxElectronModule
    ...
    ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
----

Here NgxElectronModule is also added so ElectronService can be injected wherever is needed.

After that is done, the use of hash has to be allowed so electron can reload content properly. On the `app-routing.module.ts`:

[source,TypeScript]
----
....
  imports: [RouterModule.forRoot(routes,
    {
      ....
      useHash: true,
    },
  )],
----

==== Usage
In order to use Electron in any component class the ElectronService must be injected:

[source,TypeScript]
----
import { ElectronService } from 'ngx-electron';

...

constructor(
  // other injected services
  public electronService: ElectronService,
) {
  // previous code...

  if (electronService.isElectronApp) {
    // Do electron stuff
  } else {
    // Do other web stuff
  }

}
----

TIP: A list of all accesible APIs can be found at https://github.com/ThorstenHans/ngx-electron[Thorsten Hans' ngx-electron repository].

=== Create the electron window in `main.ts`

In order to use electron, a file needs to be created at the root of the application (`main.ts`). This file will create a window with different settings checking if we are using `--serve` as an argument:

[source, typescript, linenums]
----
import { app, BrowserWindow, screen } from 'electron';
import * as path from 'path';
import * as url from 'url';

let win: BrowserWindow = null;
const args = process.argv.slice(1),
  serve = args.some(val => val === '--serve');

function createWindow(): BrowserWindow {
  const electronScreen = screen;
  const size = electronScreen.getPrimaryDisplay().workAreaSize;

  // Create the browser window.
  win = new BrowserWindow({
    x: 0,
    y: 0,
    width: size.width,
    height: size.height,
    webPreferences: {
      nodeIntegration: true,
      allowRunningInsecureContent: serve ? true : false
    }
  });

  if (serve) {
    require('electron-reload')(__dirname, {
      electron: require(`${__dirname}/node_modules/electron`)
    });
    win.loadURL('http://localhost:4200');
  } else {
    win.loadURL(
      url.format({
        pathname: path.join(__dirname, 'dist/index.html'),
        protocol: 'file:',
        slashes: true
      })
    );
  }

  if (serve) {
    win.webContents.openDevTools();
  }

  // Emitted when the window is closed.
  win.on('closed', () => {
    // Dereference the window object, usually you would store window
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    win = null;
  });

  return win;
}

try {
  // This method will be called when Electron has finished
  // initialization and is ready to create browser windows.
  // Some APIs can only be used after this event occurs.
  app.on('ready', createWindow);

  // Quit when all windows are closed.
  app.on('window-all-closed', () => {
    // On OS X it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform !== 'darwin') {
      app.quit();
    }
  });

  app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (win === null) {
      createWindow();
    }
  });
} catch (e) {
  // Catch Error
  // throw e;
}
----


=== Add the electron window and improve the `package.json` scripts

Inside `package.json` the electron window that will be transformed to `main.js` when building needs to be added.

[source,json]
----
{
  ....
  "main": "main.js",
  "scripts": {
  ....
}
----

The `scripts` section in the `package.json` can be improved to avoid running too verbose commands. `ElectronTest` in samples folder contains the following section: 

[source,json]
----
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "ng": "ng",
    "start": "npm-run-all -p electron:serve ng:serve",
    "build": "npm run electron:serve-tsc && ng build",
    "build:dev": "npm run build -- -c dev",
    "build:prod": "npm run build -- -c production",
    "ng:serve": "ng serve",
    "ng:serve:web": "ng serve -c web -o",
    "electron:serve-tsc": "tsc -p tsconfig-serve.json",
    "electron:serve": "wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve",
    "electron:local": "npm run build:prod && electron .",
    "electron:linux": "npm run build:prod && electron-builder build --linux",
    "electron:windows": "npm run build:prod && electron-builder build --windows",
    "electron:mac": "npm run build:prod && electron-builder build --mac",
    "test": "ng test",
    "e2e": "npm run build:prod && cross-env TS_NODE_PROJECT='e2e/tsconfig.e2e.json' mocha --timeout 300000 --require ts-node/register e2e/**/*.e2e.ts",
    "version": "conventional-changelog -i CHANGELOG.md -s -r 0 && git add CHANGELOG.md",
    "lint": "ng lint"
  },
----

NOTE: Some of these lines are intended to be shortcuts used in other scripts. Do not hesitate to modify them depending on your needs.

Some usage examples:

[source,bash]
----
$ npm run electron:serve                # Serve Angular app and run it inside electron
$ npm run electron:local                # Serve Angular app for production and run it inside electron
$ npm run electron:windows              # Build Angular app for production and package it for Windows OS
----
